# Generated by Django 4.2.8 on 2023-12-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lighthouse',
            name='description',
            field=models.TextField(default='Default description', max_length=250),
            preserve_default=False,
        ),
    ]
